name: Task
description: Development task
title: "[Task]: "
labels: ["type:task"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What should be done?
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Concrete work items.
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
    validations:
      required: false

