export const CHANNELS = Object.freeze({
  CONFIG_GET: "config:get",
  CONFIG_SAVE: "config:save",
  CONFIG_IMPORT_LEGACY: "config:import-legacy",
  SECRET_STATUS: "secrets:status",
  SECRET_SET: "secrets:set",
  SECRET_REMOVE: "secrets:remove",
  AI_CHAT: "ai:chat",
  AI_CANCEL: "ai:cancel",
  FEED_FETCH: "feed:fetch",
  FEED_CANCEL: "feed:cancel",
  TOPIC_FETCH: "topic:fetch",
  TOPIC_COMPLETE: "topic:complete",
  TOPIC_CANCEL: "topic:cancel",
  SPEECH_VOICEVOX_SPEAKERS: "speech:voicevox:speakers",
  SPEECH_VOICEVOX_SYNTHESIZE: "speech:voicevox:synthesize",
  SPEECH_BOUYOMI_TALK: "speech:bouyomi:talk",
  SPEECH_BOUYOMI_CLEAR: "speech:bouyomi:clear",
  SPEECH_CANCEL: "speech:cancel",
  TWITCH_START: "twitch:start",
  TWITCH_STOP: "twitch:stop",
  TWITCH_RECONNECT: "twitch:reconnect",
  PLATFORM_GET_INFO: "platform:get-info",
  WINDOW_OBS_OPEN: "window:obs:open",
  WINDOW_OBS_CLOSE: "window:obs:close",
  WINDOW_STATE_GET: "window:state:get",
  SYSTEM_OPEN_EXTERNAL: "system:open-external",
  SYSTEM_SHOW_ITEM: "system:show-item",
  SHORTCUT_STATUS: "shortcut:status",
  CAPTURE_LIST_SOURCES: "capture:list-sources",
  CAPTURE_SELECT_SOURCE: "capture:select-source",
  CAPTURE_STATUS: "capture:status",
  LOCAL_LLM_CATALOG_LIST: "local-llm:catalog:list",
  LOCAL_LLM_INSTALLED_LIST: "local-llm:installed:list",
  LOCAL_LLM_INSTALLED_GET: "local-llm:installed:get",
  LOCAL_LLM_IMPORT_BEGIN: "local-llm:import:begin",
  LOCAL_LLM_IMPORT_COMMIT: "local-llm:import:commit",
  LOCAL_LLM_IMPORT_CANCEL: "local-llm:import:cancel",
  LOCAL_LLM_DOWNLOAD_START: "local-llm:download:start",
  LOCAL_LLM_DOWNLOAD_CANCEL: "local-llm:download:cancel",
  LOCAL_LLM_DOWNLOAD_RETRY: "local-llm:download:retry",
  LOCAL_LLM_DOWNLOAD_LIST: "local-llm:download:list",
  LOCAL_LLM_DOWNLOAD_STATUS: "local-llm:download:status",
  APP_EVENT: "app:event",
  OBS_MESSAGE: "obs:message",
});

export type IpcChannel = typeof CHANNELS[keyof typeof CHANNELS];
