export const CHANNELS = Object.freeze({
  CONFIG_GET: "config:get",
  CONFIG_SAVE: "config:save",
  CONFIG_IMPORT_LEGACY: "config:import-legacy",
  SECRET_STATUS: "secrets:status",
  SECRET_SET: "secrets:set",
  SECRET_REMOVE: "secrets:remove",
  AI_CHAT: "ai:chat",
  AI_CANCEL: "ai:cancel",
  FEED_FETCH: "feed:fetch",
  FEED_CANCEL: "feed:cancel",
  TOPIC_FETCH: "topic:fetch",
  TOPIC_COMPLETE: "topic:complete",
  TOPIC_CANCEL: "topic:cancel",
  SPEECH_VOICEVOX_SPEAKERS: "speech:voicevox:speakers",
  SPEECH_VOICEVOX_SYNTHESIZE: "speech:voicevox:synthesize",
  SPEECH_BOUYOMI_TALK: "speech:bouyomi:talk",
  SPEECH_BOUYOMI_CLEAR: "speech:bouyomi:clear",
  SPEECH_CANCEL: "speech:cancel",
  TWITCH_START: "twitch:start",
  TWITCH_STOP: "twitch:stop",
  TWITCH_RECONNECT: "twitch:reconnect",
  PLATFORM_GET_INFO: "platform:get-info",
  WINDOW_OBS_OPEN: "window:obs:open",
  WINDOW_OBS_CLOSE: "window:obs:close",
  WINDOW_STATE_GET: "window:state:get",
  SYSTEM_OPEN_EXTERNAL: "system:open-external",
  SYSTEM_SHOW_ITEM: "system:show-item",
  SHORTCUT_STATUS: "shortcut:status",
  CAPTURE_LIST_SOURCES: "capture:list-sources",
  CAPTURE_SELECT_SOURCE: "capture:select-source",
  CAPTURE_STATUS: "capture:status",
  APP_EVENT: "app:event",
  OBS_MESSAGE: "obs:message",
});

export type IpcChannel = typeof CHANNELS[keyof typeof CHANNELS];
